### ISSUE TITLE
Fixits

### ISSUE THREAD

**Issue by regexident** [swiadek/pixel-perfecter-sketch-plugin#3]
Wouldn't it be nice if in addition to merely selecting imperfectly placed elements the plugin would also offer support for actually fixing the selected elements for you in a batch?

Something like `Round to nearest: 1.0` where `1.0` would be the given "grid-size" you want your stuff to be rounded to. So to allow for sub-pixels you would choose `0.5` instead, etc.

**Comment by swiadek** [comment]
Yeah, that sounds neat! You wanna give it a go?

**Comment by regexident** [comment]
Consider it done. 😎
