### ISSUE TITLE
Stopped working in recent versions of Sketch

### ISSUE THREAD

**Issue by aparajita** [swiadek/pixel-perfecter-sketch-plugin#6]
As of Sketch 46.2 (and probably earlier), the following error is logged when selecting "Select All Pixel Imperfect Layers":

TypeError: doc. currentPage(). deselectAllLayers is not a function. (In 'doc. currentPage(). deselectAllLayers()', 'doc. currentPage(). deselectAllLayers' is undefined)
line: 5
sourceURL: all.cocoascript
column: 39
stack: onRun@all.cocoascript:5:39

**Comment by swiadek** [comment]
Fixed with 1.2

**Comment by aparajita** [comment]
Awesome, thank you! Now if you supported the Sketch update mechanism, all of your users would automatically get it. 😉

**Comment by swiadek** [comment]
Honestly, I can't find time to build in support for it. I'd be happy to accept a PR from someone! ;)
